{"name": "测试数据：【 admin，True，200，success】", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'response'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04702150>, username = 'admin', except_result = True, except_code = 200, except_msg = 'success'\n\n    @allure.story(\"用例--检查登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_check_user\"])\n    def test_check_user(self, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = check_user(username)\n        step_1(username)\n        assert result.success == except_result, result.error\n>       assert result.response.status_code == 200\nE       AttributeError: 'ResultBase' object has no attribute 'response'\n\ntestcases\\api_test\\test_03_login.py:53: AttributeError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1622569693918, "stop": 1622569693919}], "attachments": [{"name": "log", "source": "fcd2cad5-75ba-480d-b4fb-e92a855f37fe-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "df3be993-e072-4f92-b89d-5d6fb6d80b91-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'success'"}], "start": 1622569693898, "stop": 1622569693920, "uuid": "f761e422-8cb9-4f75-8dcd-f261aa92ec1c", "historyId": "cd269d2fe5057f3248c70c4b9797e0a5", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "9676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}