{"name": "测试数据：【 测试test，False，1003，账号不存在，请重新输入或联系管理员！】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100022 == 1003", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04C75350>, username = '测试test', except_result = False, except_code = 1003, except_msg = '账号不存在，请重新输入或联系管理员！'\n\n    @allure.story(\"用例--检查登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_check_user\"])\n    def test_check_user(self, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = check_user(username)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json()[\"code\"]))\n        print(except_code)\n>       assert result.response.json()[\"code\"] == except_code\nE       assert 100022 == 1003\n\ntestcases\\api_test\\test_03_login.py:57: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622568741663, "stop": 1622568741663}], "attachments": [{"name": "log", "source": "0a9a5615-b477-46d7-97b8-fb4a7cb34c1b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "51cc1838-064d-448e-aa16-bab414de801a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "bf2335d5-8643-41d3-8024-282d82a662be-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1003"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622568741643, "stop": 1622568741664, "uuid": "b7e04425-7bbe-4756-a744-de6d94b41790", "historyId": "72b046043fa063fcf7c6dab29a8d3c67", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "21752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}