{"name": "测试数据：【 测试test，123456，False，100022，账号不存在，请重新输入或联系管理员！】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100017 == 100022", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04F41610>, username = '测试test', password = '123456', except_result = False, except_code = 100022, except_msg = '账号不存在，请重新输入或联系管理员！'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json()[\"code\"]))\n        # print(except_code)\n>       assert result.response.json()[\"code\"] == except_code\nE       assert 100017 == 100022\n\ntestcases\\api_test\\test_03_login.py:35: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622569998660, "stop": 1622569998661}], "attachments": [{"name": "log", "source": "d0346674-6ef0-429a-8450-8ede54c155ad-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d11ae33f-4848-4afb-b0fb-09b16b8f3fe9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "100022"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622569998638, "stop": 1622569998663, "uuid": "673eaa2c-6754-4400-85a0-fadcf5f8d9bd", "historyId": "2e858b4dcbf046901d9698feba3de5df", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--登录用户"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "18320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}