{"name": "测试数据：【 test003，False，200，账号不存在，请重新输入或联系管理员！】", "status": "broken", "statusDetails": {"message": "TypeError: 'method' object is not subscriptable", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04C79F10>, username = 'test003', except_result = False, except_code = 200, except_msg = '账号不存在，请重新输入或联系管理员！'\n\n    @allure.story(\"用例--检查登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_check_user\"])\n    def test_check_user(self, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = check_user(username)\n\ntestcases\\api_test\\test_03_login.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nusername = 'test003'\n\n    def check_user(username):\n        \"\"\"\n        检查用户登录\n        :param username: 用户名\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        result = ResultBase()\n        payload = {\n            \"username\": username\n        }\n        header = {\n            \"Content-Type\": \"application/json\"\n    \n        }\n        res = user.check(data=json.dumps(payload), headers=header)\n        result.success = False\n        if res.json()[\"code\"] == 200:\n            result.success = True\n>           result.data = res.json[\"data\"]\nE           TypeError: 'method' object is not subscriptable\n\ntestcases\\api_test\\user.py:94: TypeError"}, "description": "该用例是针对获取用户登录接口的测试", "attachments": [{"name": "log", "source": "7f36ee93-5548-4601-a8f2-b641d4ca8ea2-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4f4ce51c-9c17-4216-97d4-ab36cbfc8d1a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'test003'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622568741589, "stop": 1622568741608, "uuid": "144e7894-50f6-4463-90d5-13ee3ed7ad4f", "historyId": "38b7ba371414e38be2a72df266f3c7e7", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "21752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}