{"name": "测试数据：【 admin，True，200，您的密码不正确，请确认密码！】", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'response'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04E57950>, username = 'admin', except_result = True, except_code = 200, except_msg = '您的密码不正确，请确认密码！'\n\n    @allure.story(\"用例--检查登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_check_user\"])\n    def test_check_user(self, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = check_user(username)\n        step_1(username)\n        assert result.success == except_result, result.error\n>       assert result.response.status_code == 200\nE       AttributeError: 'ResultBase' object has no attribute 'response'\n\ntestcases\\api_test\\test_03_login.py:53: AttributeError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1622569885511, "stop": 1622569885511}], "attachments": [{"name": "log", "source": "159a8ca5-f6cd-4cc9-bddb-9dc064a7e01c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4b72d17a-e0bc-4946-9638-39cbc4ce8761-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'您的密码不正确，请确认密码！'"}], "start": 1622569885490, "stop": 1622569885512, "uuid": "ad78e34f-b1c3-41ff-a13a-7c53cd050fd0", "historyId": "dff7ccb36d9bf66fc00a8ce5e7e40002", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "21668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}