{"name": "测试数据：【 admin1，True，200，账号不存在，请重新输入或联系管理员！】", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 100022 】, 返回信息：账号不存在，请重新输入或联系管理员！ \nassert False == True\n +  where False = <core.result_base.ResultBase object at 0x04F620D0>.success", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04EA3AF0>, username = 'admin1', except_result = True, except_code = 200, except_msg = '账号不存在，请重新输入或联系管理员！'\n\n    @allure.story(\"用例--检查登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, except_result, except_code, except_msg\",\n                             api_data[\"test_check_user\"])\n    def test_check_user(self, username, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = check_user(username)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 100022 】, 返回信息：账号不存在，请重新输入或联系管理员！ \nE       assert False == True\nE        +  where False = <core.result_base.ResultBase object at 0x04F620D0>.success\n\ntestcases\\api_test\\test_03_login.py:52: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin1'"}], "start": 1622569998751, "stop": 1622569998751}], "attachments": [{"name": "log", "source": "67dfe359-35cc-40be-9987-7112299b0fbe-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6fe56d64-ce5f-4ae8-8883-f59654ef0ecd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin1'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622569998732, "stop": 1622569998752, "uuid": "6da27c07-6c2e-4e69-bab7-a5ceba9b8587", "historyId": "4544b5e87fabb355d4159c7edb332d64", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "18320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}