{"name": "测试数据：【 admin，123456，False，200，您的密码不正确，请确认密码！】", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'error'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04F1C130>, username = 'admin', password = '123456', except_result = False, except_code = 200, except_msg = '您的密码不正确，请确认密码！'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AttributeError: 'ResultBase' object has no attribute 'error'\n\ntestcases\\api_test\\test_03_login.py:30: AttributeError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1622567026161, "stop": 1622567026162}], "attachments": [{"name": "log", "source": "10252cda-fdc7-42df-99ef-74b286b0f4f5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ac46faed-677a-40e6-bbb5-9d27d61852c6-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cca13ac6-69b5-488b-9195-676c6f7d66c9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'您的密码不正确，请确认密码！'"}], "start": 1622567026107, "stop": 1622567026163, "uuid": "d8e90d57-ecb5-4858-ad7b-9c018c462ac4", "historyId": "15b3a3bd06cc736a1f476c559677576f", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "9400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}